api_keys:
  CONSUMER_KEY: "myconsumerkey"
  CONSUMER_SECRET: "myconsumersecret"
  ACCESS_TOKEN: "myaccesstoken"
  ACCESS_TOKEN_SECRET: "myaccesstokensecret"
db_options:
  host: 'localhost'
  database: 'twitter_db'
  user: 'postgres'
  password: 'mypassword'
  port: '5432'
locations:
  manhattan:
    - -74.05265808105469
    - 40.694175391548754
    - -73.81782531738281
    - 40.91091803848203