version: '3'
services:
  python_app:
    image: "localized-twitter-stream-handler:latest"
    depends_on:
      - "db"
    command: ["./wait-for-it.sh", "db:5432", "--", "python", "-m", "app.main"]
    restart: 'always'
  db:
    image: "postgres"
    container_name: "twitter_postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
      - ./postgres-data:/var/lib/postgresql/data
    restart: 'always'