version: '3'
services:
  db:
    image: "postgres"
    container_name: "twitter_postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
      - ./postgres-data:/var/lib/postgresql/data
    restart: 'always'