CREATE DATABASE twitter_db;
    \connect twitter_db;

CREATE TABLE IF NOT EXISTS twitter_user (
    id BIGINT PRIMARY KEY,
    screen_name VARCHAR NOT NULL,
    description TEXT,
    is_verified BOOLEAN NOT NULL,
    followers_count BIGINT NOT NULL,
    statuses_count BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS tweet (
    id BIGINT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    created_at_utc TIMESTAMP WITH TIME ZONE,
    location VARCHAR NOT NULL,
    replied_to_user_id BIGINT,
    replied_to_tweet_id BIGINT,
    num_hashtags SMALLINT,
    has_media BOOLEAN NOT NULL,
    text TEXT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES twitter_user (id)
);

CREATE TABLE IF NOT EXISTS hashtag (
    id BIGINT GENERATED BY DEFAULT as IDENTITY PRIMARY KEY,
    tweet_id BIGINT,
    user_id BIGINT NOT NULL,
    tag TEXT NOT NULL,
    indices SMALLINT [2] NOT NULL,
    FOREIGN KEY (tweet_id) REFERENCES tweet (id),
    FOREIGN KEY (user_id) REFERENCES twitter_user (id)
);
